version: '3'

services:
  testebuild:
    ports:
      - "80"
  samplewebappcore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

