version: '3'

services:
  testebuild:
    image: testebuild
    build:
      context: .\TesteBuild
      dockerfile: Dockerfile

  samplewebappcore:
    image: samplewebappcore
    build:
      context: .
      dockerfile: ..\SampleWebAppCore\Dockerfile

